### ISSUE TITLE
UKy Costing Progress and Refinements December 2024 to March 2025

### ISSUE THREAD

**Issue by bpaul4** [prommis/prommis#103]
- [x] Update handling of WaterTAP cost variables #110 
- [x] Add support for tax incentive and environmental benefit considerations #122 
- [x] Add support for byproduct recovery threshold considerations #123
