### ISSUE TITLE
UKy Flowsheet Refinements

### ISSUE THREAD

**Issue by MarcusHolly** [prommis/prommis#13]
- [x] Update roaster model to accept a liquid/moisture inlet @jinliangma #88 
- [x] Add `.report()` functionality to the roasting model @jinliangma #88 
- [x] Fix scaling so that no warnings are displayed when running the flowsheet #47 
- [x] Add pH adjustment blocks (mixers adding an acid or a base stream) #47 
- [x] Image should be consistent when showing mixers (we should show all) #86 
- [x] Add name of the mixers as all the other unit models #86 
- [x] Make stream naming a little more consistent or easier to follow (maybe add an extra term in name to show what part of the flowsheet we are on) #86 
- [x] Add comment on why we added eps term #86 
- [x] In the notebook we could add an explanation on the initialization loops #86
