### ISSUE TITLE
Add unit model documentation

### ISSUE THREAD

**Issue by lbianchi-lbl** [prommis/prommis#55]
Note: this is marked for the June release, but the 2.1 due date is actually **Apr 30, 2024**.

Unit models:
- [x] solvent extraction @ArkoprabhoDasgupta #69
- [x] Precipitator @agarciadiego  #62
- [x] Roaster @jinliangma #56 (more to be done in #70 in next release)
- [x] LeachTrain @andrewlee94  #60

Property models:
- [x] leaching reactions @andrewlee94  #60
- [x] leaching solids @andrewlee94  #60
- [x] leaching solutions @andrewlee94  #60
- [x] precipitator liquid @agarciadiego  #62
- [x] precipitator solids @agarciadiego  #62
- [x] SX aqueous @ArkoprabhoDasgupta #69
- [x] SX organic @ArkoprabhoDasgupta #69

Flowsheets:
- [x] UK flowsheet @MarcusHolly #61

**Comment by ksbeattie** [comment]
@jinliangma & @mollydougher any progress on your areas (roaster and nanofiltration)?

**Comment by mollydougher** [comment]
> @jinliangma & @mollydougher any progress on your areas (roaster and nanofiltration)?

@ksbeattie The nanofiltration flowsheet imports the property model `MCASParameterBlock` from WaterTAP, which should be fully documented. Is there anything else needed for the nanofiltration documentation?

**Comment by lbianchi-lbl** [comment]
@agarciadiego following up from your comment: https://github.com/prommis/prommis/pull/75#issuecomment-2090641222

Do you have an example (e.g. a screenshot) of what you mean?

**Comment by agarciadiego** [comment]
> @agarciadiego following up from your comment: [#75 (comment)](https://github.com/prommis/prommis/pull/75#issuecomment-2090641222)
> 
> > @lbianchi-lbl independent from this PR, is there a way to show the names of the models in the documentation drop-down menu instead of the name of the file?
> 
> Do you have an example (e.g. a screenshot) of what you mean?

![image](https://github.com/prommis/prommis/assets/40575271/6fa208d8-58cb-4649-9768-bcf5f3530a5c)

To have names like:

- Leach Train 
- Leach reaction 
- Leach solid properties
- etc

**Comment by lbianchi-lbl** [comment]
Oh, I see. It's a good point. I'm looking around for ways to customize the sidebar name with the method we're currently using (i.e. `:autosummary:`), without success. 

- If this is something we want to have, I think it makes sense for us to consider alternatives to the current `:autosummary:` solution to avoid the risk of "fighting the tool"
  -  e.g. maybe it's possible to use manually created files corresponding to the titles you mention, and use `:autosummary:` (or equivalent) within each of those files to populate them from the docstrings
- Unfortunately I don't have that much experience with Sphinx, but from what I know there are many overlapping solutions to do this (with confusingly similar names, e.g. `autosummary`, `autodoc`, `apidoc`, `autoapi`, ...), so I'd have to look into it more in detail
