### ISSUE TITLE
UKy Costing Progress and Refinements June To September 2024

### ISSUE THREAD

**Issue by bpaul4** [prommis/prommis#77]
To-do:

- [x] Add NPV calculation #84 
- [x] Develop diafiltration cost model #93 
- [x] Add explicit support for WaterTAP and custom cost models #90

**Comment by ksbeattie** [comment]
These came from #48 and will be for the release after June 2024
