### ISSUE TITLE
UKy Costing Progress and Refinements Prior To April 2024

### ISSUE THREAD

**Issue by bpaul4** [prommis/prommis#9]
To-do:

- [x] Initial point, revenue calculation for sales labor cost, and overnight cost updates for validation; migrated as part of #5 
- [x] Add support for water transport costing models from WaterTAP (e.g. nanofiltration, reverse osmosis, ion exchange, ...) #22 
- [x] Add case study cost models for requested applications (e.g. recycling) #24 
- [x] Add tests #10 #29 
- [x] Connect with process model flowsheet #36 
- [x] Add option to pass chemicals and waste costs as expressions #37
